# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-DeepAbstractSearch
version:      0.05
version_from: lib/Class/DBI/Plugin/DeepAbstractSearch.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Class::DBI::Plugin:            0.02
    SQL::Abstract:                 1.18
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
